// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXOzL5IWoJierDbCUFjUjEPacNj_0azBM',
    appId: '1:672703351545:web:97300d21cf33ff81607028',
    messagingSenderId: '672703351545',
    projectId: 'zadana-c3796',
    authDomain: 'zadana-c3796.firebaseapp.com',
    storageBucket: 'zadana-c3796.firebasestorage.app',
    measurementId: 'G-K49J0MG1P4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAU00qzY-ssgp3u0NhtfK8hN7NxwIvD6NE',
    appId: '1:672703351545:android:aa6991c7c1501bfd607028',
    messagingSenderId: '672703351545',
    projectId: 'zadana-c3796',
    storageBucket: 'zadana-c3796.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdLTyeoeAzdltAKkXb7r-OMuQhv76xAV8',
    appId: '1:672703351545:ios:17e4741ed8ceb201607028',
    messagingSenderId: '672703351545',
    projectId: 'zadana-c3796',
    storageBucket: 'zadana-c3796.firebasestorage.app',
    iosBundleId: 'com.example.zadanaUserV3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdLTyeoeAzdltAKkXb7r-OMuQhv76xAV8',
    appId: '1:672703351545:ios:17e4741ed8ceb201607028',
    messagingSenderId: '672703351545',
    projectId: 'zadana-c3796',
    storageBucket: 'zadana-c3796.firebasestorage.app',
    iosBundleId: 'com.example.zadanaUserV3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXOzL5IWoJierDbCUFjUjEPacNj_0azBM',
    appId: '1:672703351545:web:d5ad2070d1f003b2607028',
    messagingSenderId: '672703351545',
    projectId: 'zadana-c3796',
    authDomain: 'zadana-c3796.firebaseapp.com',
    storageBucket: 'zadana-c3796.firebasestorage.app',
    measurementId: 'G-4YRDX6PM03',
  );
}
